config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'home#index'
  get 'home/about'

  # Add this line to redirect to the login page after logout
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pin.rb
class Pin < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pins       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: %i[ show edit update destroy ]

  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /pins or /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1 or /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins or /pins.json
  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render :new
    end
  end
  

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to pin_url(@pin), notice: "Pin was successfully updated." }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url, notice: "Pin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.require(:pin).permit(:description)
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
<div class="container">
<!-- Brand and toggle get grouped for better mobile display-->
<div class="navbar-header">

<button type="button" class="navbar-toggle collapsed" data-
toggle="collapse" data-target="#bs-example-navbar-collapse-1">

<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<img src="/assets/logo.png" alt="logo" width="40" height="40">

<%= link_to 'Photo Pins', root_path, class: 'navbar-brand' %>

</div>

<!-- Collect the nav links, forms, and other content for
toggling -->

<div class="collapse navbar-collapse" id="bs-example-navbar-
collapse-1">

<ul class="nav navbar-nav navbar-right">

<li><%= link_to 'Home', root_path %></li>
<li><%= link_to 'About Us', home_about_path %></li>
<li><%= link_to 'List Pins', pins_path %></li>
  <% if user_signed_in? %>
        <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
  <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Join", new_user_registration_path %></li>
  <% end %>

</ul>

</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<div class="jumbotron text-center">
<h1>About Us</h1>
<img src="https://www.pngkit.com/png/full/354-3545064_framed-art-print-french-city-clipart.png" height=400 width=700>
<p>At Photo Pins, our mission is to provide a platform for photographers of all levels to showcase their work, connect with other photography enthusiasts, and inspire creativity. We believe that every photograph tells a unique story and deserves to be shared.</p>
</div>

app/views/home/index.html.erb
<div class="jumbotron text-center">
  <h1>Home</h1>
  <p>Welcome to Photo pins</p>
  <img src="https://media.istockphoto.com/id/545585228/vector/pictures-gallery.jpg?s=612x612&w=0&k=20&c=g5W6VxfvwIWQ7qTy0Mzi0xArS2XrxESqvEQa0KHOrvE=" height=400 width=700>
  <p>Discover and share amazing photos from around the world.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo Pins</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class="container">
        <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin) do |form| %>
  <% if pin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
        <% pin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div id="<%= dom_id pin %>">
  <p>
    <strong>Description:</strong>
    <%= pin.description %>
  </p>

</div>

app/views/pins/edit.html.erb
<div class="panel panel-default">
<div class="panel-heading"><h2>Editing pin</h2></div>
<div class="panel-body">

<%= render "form", pin: @pin %>

<br>

<div>
  <%= link_to "Show this pin", @pin %> |
  <%= link_to "Back to pins", pins_path %>
</div>
</div>
</div>

app/views/pins/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="panel panel-default">
<div class="panel-heading"><h2>Pins</h2></div>
<div class="panel-body">

<div id="pins">
  <% @pins.each do |pin| %>
    <%= render pin %>
    
    <p>
      <%= link_to "Show this pin", pin %>
    </p>
  <% end %>
</div>



<%= link_to "New pin", new_pin_path %>
</div>
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">
<div class="panel-heading"><h2>New pin</h2></div>
<div class="panel-body">

<%= render "form", pin: @pin %>

<br>

<div>
  <%= link_to "Back to pins", pins_path %>
</div>
</div>
</div>

app/views/pins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pin %>

<div>
  <%= link_to "Edit this pin", edit_pin_path(@pin) %> |
  <%= link_to "Back to pins", pins_path %>

  <%= button_to "Destroy this pin", @pin, method: :delete %>
</div>